---
rails_env: development

vm_name: url_shortener
vm_os: ubuntu/trusty64
vm_memory: 1024
vm_swap: 1024
vm_cores: 2
vm_shared_directory: /vagrant
vm_share_type: NFS
vm_ip: 192.168.20.50
package_bundles:
  - curl
  - graphics
  - qt
packages:
  - curl
  - libcurl3
  - libcurl3-gnutls
  - libcurl4-openssl-dev
  - imagemagick
  - qt5-default
  - libqt5webkit5-dev
manual_ruby_version: 
server_name: localhost
rails_version: 4
ruby_install: rvm
ruby_version: 2.2.0
environment_file: /vagrant/.envrc
databases:
  - postgresql
background_jobs:
postgresql_orm: none
mysql_orm: none
mongodb_orm: none
redis_orm: none
mongodb_db_name: myapp
mysql_db_name: myapp
mysql_db_user: vagrant
mysql_db_password: 
postgresql_db_name: url_shortener
postgresql_db_user: vagrant
postgresql_db_password: 
postgresql_extensions:
  - hstore
delayed_job_command: script/delayed_job run
sidekiq_command: sidekiq
resque_command: rake resque:work
server_type: nginx_unicorn
autoconf: true

app_name: '{{ vm_name }}'
user_name: vagrant
group_name: vagrant

user_home_path: '/home/{{ user_name }}'

ssl_certificate_path: /etc/nginx/ssl/{{ server_name }}.crt
ssl_certificate_key_path: /etc/nginx/ssl/{{ server_name }}.key

app_path: '{{ vm_shared_directory }}'
app_public_path: "{{ app_path }}/public"
app_config_path: "{{ app_path }}/config"
app_temp_path: "{{ app_path }}/tmp"
app_logs_path: "{{ app_path }}/log"

unicorn_sock_path: "/tmp/unicorn.{{ rails_env }}.sock"
unicorn_config_path: "{{ app_config_path }}/unicorn.{{ rails_env }}.rb"
unicorn_pid_path: "{{ app_temp_path }}/unicorn.{{ rails_env }}.pid"
unicorn_stderr_path: "{{ app_logs_path }}/unicorn.err.log"
unicorn_stdout_path: "{{ app_logs_path }}/unicorn.log"

ruby_user_name: '{{ "root" if ruby_install == "package" else user_name }}'

use_apt_proxy: false
